[project]
name = "streamlit-kruscotto-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas==2.3.0",
    "plotly==6.2",
    "pytest==8.4.2",
    "streamlit==1.47.0",
    "supabase==2.16",
]
